#Dockerfileを用いない場合の設定ファイル
version: '3.8'
services:
  python3:
    #コンテナ名
    container_name: "eppstein"
    #ビルド指定(どのDockerfileをビルドするか)
    build: .
    image: eppstein
    # build -> imageの順に実行
    # この場合, imageに指定した名前がimage名になる
    
    working_dir: "/app/"
    #マウント設定
    volumes: 
      - ./app:/app/
    #起動永続
    tty: true